"""Constants for the Resol KM1/KM2, DL2/DL2Plus/DL3, VBus/LAN, VBus/USB component."""

DOMAIN = "deltasol"
DEFAULT_NAME = "Resol KM1/KM2, DL2/DL2Plus/DL3, VBus/LAN, VBus/USB"
DEFAULT_TIMEOUT = 60

DEFAULT_SCAN_INTERVAL = 300
MIN_SCAN_INTERVAL = 60

DEFAULT_PORT = 80
DEFAULT_USERNAME = "admin"
